services:
  autoresearching-ai-dev-chat-local:
    container_name: autoresearching-ai-dev-chat-local
    image: autoresearching-ai-dev-chat-local:latest
    user: root
    network_mode: "host"
    restart: always
    env_file:
      - .env
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: ["python", "main_chat_local.py"]

  autoresearching-ai-dev-doc-local:
      container_name: autoresearching-ai-dev-doc-local
      image: autoresearching-ai-dev-doc-local:latest
      user: root
      network_mode: "host"
      restart: always
      env_file:
        - .env
      build:
        dockerfile: ./Dockerfile
        context: .
      volumes:
        - /etc/localtime:/etc/localtime:ro
      command: ["python", "main_doc_local.py"]

  autoresearching-ai-dev-enhance-local:
      container_name: autoresearching-ai-dev-enhance-local
      image: autoresearching-ai-dev-enhance-local:latest
      user: root
      network_mode: "host"
      restart: always
      env_file:
        - .env
      build:
        dockerfile: ./Dockerfile
        context: .
      volumes:
        - /etc/localtime:/etc/localtime:ro
      command: ["python", "main_enhance_local.py"]

  autoresearching-ai-dev-write-local:
      container_name: autoresearching-ai-dev-write-local
      image: autoresearching-ai-dev-write-local:latest
      user: root
      network_mode: "host"
      restart: always
      env_file:
        - .env
      build:
        dockerfile: ./Dockerfile
        context: .
      volumes:
        - /etc/localtime:/etc/localtime:ro
      command: ["python", "main_write_local.py"]
