services:
  autoresearching-ai-dev-enhance:
    container_name: autoresearching-ai-dev-enhance
    image: autoresearching-ai-dev-enhance:latest
    user: root
    network_mode: "host"
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: ["python", "main_enhance.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10g"
        max-file: "2"