LANGUAGE_KIT = {
    "tiếng việt": {
        "unused_paper": "Tài liệu không được sử dụng trong bài viết này",
        "Paper's Usage": "Tổng hợp tài liệu trích dẫn",
        "No.": "STT",
        "Quality": "Chất lượng học thuật",
        "Title - Authors - Year": "Tên đề tài - Tác giả - Năm",
        "Title": "Tên tài liệu",
        "Authors": "Tác giả",
        "Year": "Năm",
        "Use in": "Trích dẫn vào chương",
        "Usage": "Nội dung trích dẫn",
        "Note": "Ghi chú",
        "Relationship Graph": "Mô hình nghiên cứu",
        "Table": "Bảng",
        "Figure": "Hình",
        "References": "Tài liệu tham khảo",
        "APPENDICES": "PHỤ LỤC",
        "APPENDIX 1. LIST OF TABLES, FIGURES, DIAGRAMS": "PHỤ LỤC 1. DANH MỤC CÁC BẢNG, HÌNH, BIỂU ĐỒ",
        "APPENDIX 2. RESEARCH TOOLS (QUESTIONNAIRE / INTERVIEW / SCALE)": "PHỤ LỤC 2. CÔNG CỤ NGHIÊN CỨU (BẢNG HỎI / PHỎNG VẤN / THANG ĐO)",
        "APPENDIX 3. LIST OF SCALES AND ORIGINAL REFERENCES": "PHỤ LỤC 3. DANH MỤC THANG ĐO VÀ NGUỒN THAM KHẢO GỐC",
        "APPENDIX 4. STATISTICAL TEST RESULTS": "PHỤ LỤC 4. KẾT QUẢ KIỂM ĐỊNH THỐNG KÊ",
        "APPENDIX 5. SURVEY DATA (RAW DATA SUMMARY)": "PHỤ LỤC 5. DỮ LIỆU KHẢO SÁT (RAW DATA SUMMARY)",
        "APPENDIX 6. IN-DEPTH INTERVIEW RESULTS (IF ANY)": "PHỤ LỤC 6. KẾT QUẢ PHỎNG VẤN SÂU (NẾU CÓ)",
        "APPENDIX 7. CALCULATION FORMULA / MODELING": "PHỤ LỤC 7. CÔNG THỨC TÍNH TOÁN / MÔ HÌNH HÓA",
        "APPENDIX 8. RELATED DOCUMENTS, POLICIES, RESOLUTIONS": "PHỤ LỤC 8. CÁC TÀI LIỆU, CHÍNH SÁCH, NGHỊ QUYẾT LIÊN QUAN",
        "APPENDIX 9. RESEARCH ETHICS PROCESS": "PHỤ LỤC 9. QUY TRÌNH ĐẠO ĐỨC NGHIÊN CỨU",
        "APPENDIX 10. IMPLEMENTATION PLAN AND SCHEDULE (GANTT CHART)": "PHỤ LỤC 10. KẾ HOẠCH TRIỂN KHAI VÀ TIẾN ĐỘ (GANTT CHART)",
        "APPENDIX 11. LIST OF ABBREVIATIONS / SYMBOLS": "PHỤ LỤC 11. DANH MỤC TỪ VIẾT TẮT / KÝ HIỆU",
        "propose_method_table": "Bảng thiết kế nghiên cứu",
        "propose_method_name": "Tên biến",
        "propose_method_variable_type": "Loại biến",
        "propose_method_measurement_type": "Kiểu đo lường",
        "propose_method_description": "Miêu tả biến",
        "propose_method_scale": "Thang đo",
        "propose_method_variable_code": "Mã hóa biến",
        "propose_method_question": "Câu hỏi",
        "propose_method_question_code": "Mã câu hỏi",
        "propose_method_indicator_name": "Tên chỉ báo",
        "propose_method_answer_content": "Nội dung trả lời", 
        "propose_method_survey_questions_table": "Bảng câu hỏi khảo sát",
        "propose_method_survey_variables_table": "Bảng thang đo",
        "propose_method_survey_list": "Danh sách",
        "propose_method_source": "Nguồn",
        "propose_method_survey_questions": "Câu hỏi khảo sát",
        "propose_method_questions": "Câu hỏi nghiên cứu",
        "propose_method_questions_table": "Bảng câu hỏi nghiên cứu",
        "latent": "Tiềm ẩn",
        "observable": "Quan sát",
        "clear_and_simple": "Rõ ràng và dễ hiểu",
        "narrow_in_scope": "Phạm vi hẹp, tập trung",
        "feasible": "Khả thi trong nghiên cứu",
        "grounded_in_practice": "Gắn với thực tiễn",
        "highly_practical": "Tính thực tiễn cao",
        "clear_novelty": "Có yếu tố mới rõ ràng",
        "clear_research_model": "Mô hình nghiên cứu rõ ràng",
        "methodologically_sound": "Phù hợp về mặt phương pháp",
        "high_originality": "Tính sáng tạo cao, độc đáo",
        "major_contribution": "Đóng góp lớn về lý thuyết hoặc thực tiễn",
        "global_relevance_and_scope": "Tính liên quan và phạm vi toàn cầu",
        "methodological_rigor": "Độ nghiêm ngặt về phương pháp luận",
        "Original design": "autoresearching đề xuất",
        "- subsection ": "- Tiểu mục con ",
        "- what to write for subsection ": "- Những gì cần viết cho tiểu mục con ",
    },
    "english": {
        "clear_and_simple": "Clear and simple",
        "narrow_in_scope": "Narrow in scope",
        "feasible": "Feasible",
        "grounded_in_practice": "Grounded in practice",
        "highly_practical": "Highly practical",
        "clear_novelty": "Clear novelty",
        "clear_research_model": "Clear research model",
        "methodologically_sound": "Methodologically sound",
        "high_originality": "High originality",
        "major_contribution": "Major contribution",
        "global_relevance_and_scope": "Global relevance and scope",
        "methodological_rigor": "Methodological rigor",
        "unused_paper": "This document is not used in this report",
        "Paper's Usage": "Paper's Usage",
        "No.": "No.",
        "Quality": "Quality",
        "Title - Authors - Year": "Title - Authors - Year",
        "Title": "Title",
        "Authors": "Authors",
        "Year": "Year",
        "Use in": "Use in",
        "Usage": "Usage",
        "Note": "Note",
        "Relationship Graph": "Relationship Graph",
        "Table": "Table",
        "Figure": "Figure",
        "References": "References",
        "APPENDICES": "APPENDICES",
        "APPENDIX 1. LIST OF TABLES, FIGURES, DIAGRAMS": "APPENDIX 1. LIST OF TABLES, FIGURES, DIAGRAMS",
        "APPENDIX 2. RESEARCH TOOLS (QUESTIONNAIRE / INTERVIEW / SCALE)": "APPENDIX 2. RESEARCH TOOLS (QUESTIONNAIRE / INTERVIEW / SCALE)",
        "APPENDIX 3. LIST OF SCALES AND ORIGINAL REFERENCES": "APPENDIX 3. LIST OF SCALES AND ORIGINAL REFERENCES",
        "APPENDIX 4. STATISTICAL TEST RESULTS": "APPENDIX 4. STATISTICAL TEST RESULTS",
        "APPENDIX 5. SURVEY DATA (RAW DATA SUMMARY)": "APPENDIX 5. SURVEY DATA (RAW DATA SUMMARY)",
        "APPENDIX 6. IN-DEPTH INTERVIEW RESULTS (IF ANY)": "APPENDIX 6. IN-DEPTH INTERVIEW RESULTS (IF ANY)",
        "APPENDIX 7. CALCULATION FORMULA / MODELING": "APPENDIX 7. CALCULATION FORMULA / MODELING",
        "APPENDIX 8. RELATED DOCUMENTS, POLICIES, RESOLUTIONS": "APPENDIX 8. RELATED DOCUMENTS, POLICIES, RESOLUTIONS",
        "APPENDIX 9. RESEARCH ETHICS PROCESS": "APPENDIX 9. RESEARCH ETHICS PROCESS",
        "APPENDIX 10. IMPLEMENTATION PLAN AND SCHEDULE (GANTT CHART)": "APPENDIX 10. IMPLEMENTATION PLAN AND SCHEDULE (GANTT CHART)",
        "APPENDIX 11. LIST OF ABBREVIATIONS / SYMBOLS": "APPENDIX 11. LIST OF ABBREVIATIONS / SYMBOLS",
        "propose_method_table": "Research design table",
        "propose_method_name": "Variable's name",
        "propose_method_variable_type": "Variable's type",
        "propose_method_measurement_type": "Measurement's type",
        "propose_method_description": "Variable's description",
        "propose_method_scale": "Scale",
        "propose_method_variable_code": "Variable's code",
        "propose_method_question": "Question",
        "propose_method_question_code": "Question's code",
        "propose_method_indicator_name": "Indicator's name",
        "propose_method_answer_content": "Answer content",
        "propose_method_survey_questions_table": "Survey questions table",
        "propose_method_survey_variables_table": "Survey variables table",
        "propose_method_survey_list": "List of",
        "propose_method_source": "Source",
        "propose_method_survey_questions": "Survey questions",
        "propose_method_questions": "Research questions",
        "propose_method_questions_table": "Research questions table",
        "latent": "Latent",
        "observable": "Observable",
        "Original design": "autoresearching suggested",
        "- subsection ": "- Subsection ",
        "- what to write for subsection ": "- What to write for Subsection ",
    }
}