from datetime import datetime
import logging
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI

from document_setup.src.modules.knowledge_prompt_bank import KNOWLEDGE_BASE_PROMPT, RESEARCH_PLAN_PROMPT, RESEARCH_PLAN_PROMPT_V2
from get_llm_response import get_answer, get_answer_with_schema, get_answer_with_websearch
from document_setup.src.schemas.search_web import ResearchPlan

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

logger = logging.getLogger(__name__)


class SearchWeb():
    """
    Handles planning and constructing a knowledge base via web search simulation.

    Uses a language model client (initialized externally, e.g., OpenAI or Gemini)
    to generate a research plan and then synthesize a knowledge base report based on that plan.

    Attributes:
        client: An instance of the language model client (OpenAI or genai.Client).
        model_id (str): Identifier for the language model used by the client.
    """
    def __init__(
        self, 
        document_id: str,
        model_id: str, 
        llm: ChatOpenAI | ChatGoogleGenerativeAI, 
        search_web_key: str,
        use_web_search: bool,
    ):
        """
        Initializes the SearchWeb class.

        Args:
            model_id (str): The identifier of the language model to use.
            client: An initialized language model client instance (OpenAI or genai.Client).
        """
        self.llm = llm
        self.search_web_key = search_web_key
        self.use_web_search = use_web_search
        self.model_id = model_id
        self.input_tokens = 0
        self.output_tokens = 0
        self.web_search_call = 0

    async def plan_knowledge_base(
        self, 
        topic: dict,
        field: str,
        domains: list[str], 
        keywords: dict
    ) -> ResearchPlan:
        """
        Generates a research plan based on the user's query using the LLM.

        Args:
            query (str): The user's research query.

        Returns:
            ResearchPlan: A Pydantic model instance containing the original query
                          and a structured research plan with steps and sub-queries.
        """
        content = f"User's topic: {topic}\nUser's field: {field}\nUser's domains: {domains}\nKeywords: {keywords}"
        result, input_tokens, output_tokens = await get_answer_with_schema( 
            self.document_id[:8],
            self.llm, 
            RESEARCH_PLAN_PROMPT, 
            content, 
            ResearchPlan
        )
        self.input_tokens += input_tokens
        self.output_tokens += output_tokens
        return result
    
    async def plan_knowledge_base_v2(
        self, 
        field: str,
        domain: str, 
        subdomain: str,
    ) -> ResearchPlan | str:
        """
        Generates a research plan based on the user's query using the LLM.

        Args:
            query (str): The user's research query.

        Returns:
            ResearchPlan: A Pydantic model instance containing the original query
                          and a structured research plan with steps and sub-queries.
        """
        content = f"User's field: {field}\nUser's domains: {domain}\nUser's subdomains: {subdomain}"
        error, success, result, input_tokens, output_tokens = await get_answer_with_schema( 
            self.document_id[:8],
            self.llm, 
            RESEARCH_PLAN_PROMPT_V2, 
            content, 
            ResearchPlan
        )
        if not success:
            if error.status_code in [401, 403, 429, 500]:
                raise error
            logger.info(f"[{self.document_id[:8]}] Fail to generate research plan for {subdomain}")
            result = f"Current trend and up-to-date knowledge for {subdomain}"
        return result, input_tokens, output_tokens

    async def construct_knowledge_base(self, plan: ResearchPlan | str) -> tuple[str, int, int, int]:
        """
        Constructs a knowledge base report based on the provided research plan using the LLM.

        Simulates executing the research plan and synthesizes the findings into a
        detailed report string.

        Args:
            plan (ResearchPlan): The research plan generated by `plan_knowledge_base`.

        Returns:
            str: A string containing the detailed knowledge base report generated by the LLM.
        """
        retry = 0
        content = f"User's plan: {plan}\n Current date: {datetime.now().strftime("%a %b %-d, %Y")}"
        if self.use_web_search:
            error, success, result, retry, input_tokens, output_tokens = await get_answer_with_websearch(
                self.document_id[:8],
                self.llm,
                KNOWLEDGE_BASE_PROMPT, 
                content,
                self.search_web_key,
                "english",
                plan,
            )
            
            if not success:
                raise error
        else:
            error, success, result, input_tokens, output_tokens = await get_answer(
                self.document_id[:8],
                self.llm,
                KNOWLEDGE_BASE_PROMPT + "\n" + content, 
            )
            if not success:
                raise error
        return result, input_tokens, output_tokens, retry
